# Generated by Django 2.2.3 on 2019-07-03 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name_plural': 'Videos'},
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='title',
            new_name='url',
        ),
    ]
