# Generated by Django 2.2.3 on 2019-07-03 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20190703_0522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='url',
            new_name='link',
        ),
    ]
